### ISSUE TITLE
Error gitproject title

### ISSUE THREAD

**Issue by oysor** [gitical/realtime-multiplayer-game-with-websockets#1]
The repository name `'turn-based-multiplayer-with-REST-and-SSE'` is misleading?

**Comment by gitical** [comment]
Agree, maybe` realtime-multiplayer-game-with-websockets`?

**Comment by oysor** [comment]
Sounds good!On 18.09.2020, 10:20 gitical <notifications@github.com> wrote:

   
  Agree, maybe realtime-multiplayer-game-with-websockets?
